FROM node:24-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

ENV NODE_ENV=development

CMD ["pnpm", "typeorm:migration:run", "&&", "pnpm", "start:dev"]